### ISSUE TITLE
Register at Packagist and hook into repo

### ISSUE THREAD

**Issue by philwareham** [etc-plugins/etc_cache#1]
Hi @bloatware - can you register this repo with Packagist using your account there and hook up as per what we did on etc_paginate. I can then test the Composer installation works.

Cheers, Phil.

**Comment by bloatware** [comment]
Done (?)

**Comment by philwareham** [comment]
I'm not seeing etc_cache on Packagist as yet? Can you confirm? You'd need to submit the Package https://packagist.org/packages/submit

**Comment by bloatware** [comment]
I don't seem to be a maintainer of [https://packagist.org/packages/etc-plugins/](https://packagist.org/packages/etc-plugins/), can't submit anything :-)

**Comment by philwareham** [comment]
Oh ok, I’ve now done the Packagist stuff. Will test installation when I’m next st computer (Wednesday). Cheers.
